* find key binding
** M-x describe-bindings
there are some other nice ways to see key bindings
** M-x describe-prefix-map
Lists all the bindings currently available, use isearch, occur, etc. to make good use of this list.
** M-x describe-mode
This shows all the bindings available from the current mode, you can use the display buffer as you would any other readonly Emacs buffer, for example you can search freely for strings etc.
** M-x describe-minor-mode
As well as giving you general info about the current mode, it will also list all the key bindings available.
You will be prompted to enter the name of a minor mode, and then be shown info and key bindings for that minor mode.

* I bind jump-to-prev-pos and jump-to-next-pos to C-< and C->
https://www.emacswiki.org/emacs/JumpToPrevPos

* mark ring
https://www.gnu.org/software/emacs/manual/html_node/emacs/Mark-Ring.html#Mark-Ring

* Symbol References (c language)
https://www.gnu.org/software/emacs/manual/html_node/semantic/SymRef.html
* go to last update
https://www.emacswiki.org/emacs/GotoLastChange
* find function key bind
  [[file:find_function.org][find function define in emacs]]

* M-. find tage
** generate tag 
1. [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Create-Tags-Table.html][etag usage]]
2. M-.


* bebug key
https://www.gnu.org/software/emacs/manual/html_node/emacs/Commands-of-GUD.html

** C-x C-a C-b=> Set a breakpoint on the source line that point is on.
i prefer use  in  IntellJ=> C-S-a  C-b

