* Netwrok manager always override resolv.conf ?
When reboot, /etc/resolv.conf setting are changed as:
#+BEGIN_SRC conf
  # Generated by NetworkManager
  search fenrir.org
  nameserver 8.8.8.8
#+END_SRC
** solution:
*** if use pppoe-setup, and pppoe-start to connect nwtwork:
**** find ifcfg-xxx setting
 #+BEGIN_SRC shell
   [fenrir@fenrir ~]$ sudo grep DNS /etc/sysconfig/network-scripts/ifcfg-*
   /etc/sysconfig/network-scripts/ifcfg-ppp0:PEERDNS=no
   /etc/sysconfig/network-scripts/ifcfg-ppp0.bak:PEERDNS=yes
 #+END_SRC
**** modify /etc/sysconfig/network-scripts/ifcfg-ppp0
 Copy setting into /etc/sysconfig/network-scripts/ifcfg-default-dhcp.
 Pppoe can not work on boot time, we use another setting :ifcfg-default-dhcp to overrid /etc/resolv.conf
 - PEERDNS=answer
   where answer is one of the following:
   yes — Modify /etc/resolv.conf if the DNS directive is set, if using DHCP, or if using Microsoft's RFC 1877 IPCP extensions with PPP. In all cases yes is the default.
   no — Do not modify /etc/resolv.conf.
 - DNS{1,2}=address
   where address is a name server address to be placed in /etc/resolv.conf provided that the PEERDNS directive is not set to no. 
#+BEGIN_SRC conf
  TYPE=Ethernet
  PROXY_METHOD=none
  BROWSER_ONLY=no
  BOOTPROTO=dhcp
  DEFROUTE=yes
  PEERDNS=no
  IPV4_FAILURE_FATAL=no
  IPV6INIT=yes
  IPV6_AUTOCONF=yes
  IPV6_DEFROUTE=yes
  IPV6_FAILURE_FATAL=no
  IPV6_ADDR_GEN_MODE=stable-privacy
  NAME="default setting on boot"
  UUID=616e72fa-e208-358c-8567-d0eae408e989
  DEVICE=enp0s31f6
  ONBOOT=yes
  AUTOCONNECT_PRIORITY=-999
  DNS1=8.8.8.8
  DNS2=8.8.8.4
  IPV6_PEERDNS=no
#+END_SRC
**** reboot
#+BEGIN_SRC shell
sudo reboot
#+END_SRC
*** reference:
[[https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/s1-networkscripts-interfaces][redhet's interface configuration files]]
