* 隨便甚麼都好，說得天花亂墜也好， 當女生找到共鳴的時候，恭喜你，你成功把開關打開了!
久久沒寫文章了
這段時間，網友們都在問
到底要怎麼跟女生交談才會熱絡
對我來說這是一件很簡單的事情
因為已經習慣成自然了
但是還是說明一下我的作法，當然跟前幾篇一樣，
最主要的還是要練習
要熱絡不外乎引導式與誘發性
引導式通常我會用在問題上
誘發性通常我會用在回答上
一起使用通常會用在分享上
** 引導式的問題
一般來說這邊我通常是不會用在要"對方資料"上面
簡單的說，越是無關痛癢的問題，女生會回答得越沒有壓力。
越是容易被答的問題，就可以當開頭用的詞彙...
而且通常我都是利用慰問的方式
例如:今天天氣真好耶、吃飽了嗎、身體好多了嗎....等
當女生回答完後，才是展開話題的重點。
** 誘發性的回答
這邊嘛，說的抽象一點就是套話拉，
"對方資料"，我都是在這邊慢慢套出來，
既然這邊是有利益關係，所以你也要付出相當的代價囉，
不管你怎麼想，"讚美"永遠是付予女生最大的利益，
在簡單的說，誘拐小妹妹你也要給糖吃吧...舉個例子:
 我:嘿嘿，今天買了好多保養品~~
 女生:你買這麼多保養品要幹嘛阿?
 我:想變得跟妳一樣漂亮啊~~
 女生:阿??怎麼會這麼娘阿你..
 我:哈哈，開玩笑的，有些是幫媽媽藏起來的戰利品。
 不過我媽跟妳一樣漂亮的話這些應該也用不到吧~~
 女生:呵呵，原來是這樣喔，哎呀我也有在用阿。
 我:是喔，那推薦一些吧，我可以順便跟我媽媽說，說不定她就能跟妳一樣了呢~~
 女生:!*&(*$^!@&^$*!@^$(基本上這邊女生會開始推薦)。
 我:原來如此，我記得有些專櫃新光三越信義A8~A11我有看過耶。
 女生:對阿，那邊通常周年慶我才會去買，平常我都是網路訂比較便宜。
 我:恩恩，聽說專櫃跟網路價有些會差到1/3以上。
以下不再多說(因為會很長所以通常我會聊到一個斷點而已。)
當然這只是其中一個例子。
這種套話式對話真的要憑"經驗"
上面我套出對方，有在使用保養品的習慣以及她採購的方式。
知道這些可以幹嘛
可以慢慢了解他的生活方式
可以用這個方向邀約她去一些"打折"商品的地方採買
沒話題聊時，可以繞回這個主線(基本上這邊是用不到啦)。
分享永遠是挑撥女人說話開關的利器
當真的沒話題可以聊的時候，
你又不知道該怎麼去套女生的話，
又覺得"讚美"是種"奉承與膚淺"的東西的話，
請跟對方分享你的生活、經驗、有趣的事情。
如果你的生活、經驗、有趣的事情，都是圍繞著3C、電玩的話，
不要怪我，你只有被發卡的份。
任何事情都可以分享，小至路邊帶狗散步的人，大至人生經驗...
隨便甚麼都好，說得天花亂墜也好，
當女生找到共鳴的時候，恭喜你，你成功把開關打開了。

** 結論:
女人是種不愛思考的動物，
越是機械式的反應，她們越能接受，
所以引導她們思考是種很重要的工作，
女人在意也只有她想聽到的話而已，
其他你說得天花亂墜的，她們也不會去記住，
所以"甜蜜鬼話"多學學練練，應用自如，
開關，隨便一按就開了。
