* monitor file cahnge
** inotify 
Inotify Watches Limit
Skip to end of metadata
Created by Roman Shevchenko, last modified by Peter Gromov on Aug 03, 2016 Go to start of metadata
For an intelligent IDE, it is essential to be in the know about any external changes in files it is working with - e.g. changes made by VCS, or build tools, or code generators etc. For that reason, IntelliJ platform spins background process to monitor such changes. The method it uses is platform-specific, and on Linux, it is the Inotify facility.

Inotify requires a "watch handle" to be set for each directory in the project. Unfortunately, the default limit of watch handles may not be enough for reasonably sized projects, and reaching the limit will force IntelliJ platform to fall back to recursive scans of directory trees.

To prevent this situation it is recommended to increase the watches limit (to, say, 512K):

1. Add the following line to either /etc/sysctl.conf file or a new *.conf file (e.g. idea.conf) under /etc/sysctl.d/ directory:

#+BEGIN_SRC 
fs.inotify.max_user_watches = 524288
#+END_SRC

2. Then run this command to apply the change:

#+BEGIN_SRC 
sudo sysctl -p --system
#+END_SRC

* what process useing file
#+BEGIN_SRC 
fuser fileName
#+END_SRC
